---
title: "Lab 08 - Under Constuction"
author: "KEY"
date: "`r Sys.Date()`"
output: html_document
---

```{r load-packages, message = FALSE, warning=FALSE, echo = FALSE}
library(emo)
#devtools::install_github("hadley/emo")
```

This solutions key for the IDS lab is currently under construction. 👷🔨

Please return back to this page later in the course.


## In the meantime...

Have a look at the following data from the `datasauRus` package. Each data set has the same mean, variance and correlation values, but they all look different!



```{r datasuRus, message = FALSE, fig.height=10}
library(datasauRus)
library(tidyverse)
library(ggplot2)

ggplot(datasaurus_dozen, aes(x = x, y = y, colour = dataset))+
    geom_point()+
    theme(legend.position = "none")+
    facet_wrap(~dataset, ncol = 3)

datasaurus_dozen %>% 
    group_by(dataset) %>% 
    summarize(
      mean_x    = mean(x),
      mean_y    = mean(y),
      std_dev_x = sd(x),
      std_dev_y = sd(y),
      corr_x_y  = cor(x, y)
    )
```