---
title: "Lab 00 - Hello IDS!"
author: "INSERT TEAM NAME HERE"
date: "`r Sys.Date()`"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 13--17

We set up the data frame.

```{r setup-tibble}
usernames <- c("wilsonamy", "username 1", "username 2", "username 3", "username 4") #Extend if necessary
nums <- c(18, NA, NA, NA, NA) #Extend if necessary
colours <- c("powderblue", "Colour 1", "colour 2", "colour 2", "colour 4") #Extend if necessary
hobbies <- c("Hiking", "Hobby 1", "Hobby 2", "Hobby 3", "Hobby 4") #Extend if necessary

team_data <- tibble(username = usernames, die_roll = nums, colour = colours,
                    hobby = hobbies)
```

### Exercise 18
We now work on visualising our data.

```{r bar-plot}
# Uncomment the three lines below
# p1 <- ggplot(team_data, aes(x = username, y = die_roll)) +
#   geom_col(fill = team_data$colour)
# p1
```

### Exercise 19

*Remove this text (including the stars), and add your answer for Exercise 19 here.*

### Exercises 20--21

```{r labelled-bar-plot}
# Uncomment the three lines below
# p1 +
#   labs(x = "Insert text here", y = "Insert text here",
#        title = "Insert text here")
```

*Remove this text (including the stars), and add your answer for Exercise 21 here.*

### Exercise 22

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

*Remove this text (including the stars) and add your answer for Exercise 22 here.*
