---
title: "Lab 00 - Hello IDS!"
author: "KEY"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Bugs Bunny", "White Rabbit", 
           "Judy Hopps", "Thumper"),
  github_username = c("mcgregors-garden", "whats-up-doc", "Im-late", 
                      "have-to-try", "say-nothing"), 
  colour = c("powderblue", "darkorange", "white", 
             "seagreen1", "plum"),
  hobby = c("Hopping", "Comedy", "Tailoring", 
            "Driving", "Drumming"),
  favourite_number = c(2, 8, 5, 7, 10)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The code generates a bar plot if each member's favourite number with the colour of each bar representing the team member's favourite colour.
